controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

landing:
  path: /
  controller: App\Web\Landing\UI\Controller\LandingController
  methods: GET|HEAD

hello:
  path: /hello
  controller: App\Controller\HelloController::hello
  methods: GET|HEAD

bye:
  path: /bye
  controller: App\Controller\ByeController::bye
  methods: GET|HEAD
